### ISSUE TITLE
mmal_vc_component_enable: failed to enable component: ENOSPC

### ISSUE THREAD

**Issue by EddieOne** [stetsmando/pi-camera#15]
However, when I run ` raspistill -o cam.jpg` it works fine.

```
var captureImage = () => {
  myCamera.snap().then((result) => {
    captureImage();
  })
  .catch((error) => {
     console.log(error)
  });
}
```

Seems to work but doesn't want to capture in series

**Comment by stetsmando** [comment]
Hey, @EddieOne 👋 

This issues seems very similar (identical) to something [I encountered a few years ago](https://github.com/stetsmando/pi-motion-detection/issues/1). I was building this project to support another project I was working on. I encountered the issue when calling the camera module too frequently.

Ultimately I believe the issue is related to the pi's camera and not the JavaScript code calling it. Because I was able to produce similar errors just using the native Python libraries. You could possibly try calling the `snap` function less frequently and seeing if that helps.

I wish I had more info, but I haven't really worked on anything pi related in a few years so I'm not in a position to debug this.

**Comment by EddieOne** [comment]
I ended up using pi-camera-connect and that seems to work better
